# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Game of Life' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Game of Life
  # pod 'CircleMenu', '~> 1.0.0'
  # pod 'ContextMenu.iOS'
#  pod 'SideMenu'
end
